theme: jekyll-theme-minimal
title: Calnix
logo: /assets/calnix.png
description: Queries? Ping post [at] calnix [dot] dev.
baseurl: "" 
url: "https://calnix.dev"
plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
exclude:
  - README.md
github:
  is_project_page: false
  is_user_page: false

json:
  name: Calnix
  description: data potato
  current status: employed

  message: 	
      - Greetings!
      - You appear to be lost...
      - Do you need help?
  contact:
    email: post[at]calnix[dot]dev
    
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
